apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
  labels:
    tier: front-end

spec:
  template:
    metadata:
      labels: 
        tier: front-end
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 2
  selector:
    matchLabels:
      tier: front-end