apiVersion: v1
kind: ReplicaSet
metadata:
  name: rs-kk

spec:
  template:
    metadata:
      name: nginx
      labels:
        tier: backend
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
  replicas: 4
  selector:
    matchLabels:
      tier: backend  

            