name: build_deploy_aks_azure-vote-v2

on:
  push:
    paths:
      - "azure-vote-v2/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3

      # Azure Container Registry (ACR) build - Remove this step as it's no longer needed

      # Azure login
      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Set AKS context
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.resource_group }}
          cluster-name: ${{ secrets.cluster_name }}

      # Setup kubectl
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3

      # Deploy to AKS
      - name: Deploy to AKS
        id: deploy-aks
        uses: Azure/k8s-deploy@v4
        with:
          namespace: default
          manifests: |
            pods/postgres-pod.yaml
            pods/redis-pod.yaml
            pods/result-app-pod.yaml
            pods/voting-app-pod.yaml
            pods/worker-app-pod.yaml
            services/postgres-service.yaml
            services/redis-service.yaml
            services/result-app-service.yaml
            services/voting-app-service.yaml
          images: ${{ secrets.registry }}.azurecr.io/${{ secrets.repository }}/azure-vote-v2:${{ github.sha }}
          pull-images: true
