name: build_deploy_aks_azure-vote-v2

on:
  push:
    paths:
      - "kk/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3

      # Azure login
      - name: Azure login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Set AKS context
      - name: Set AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.resource_group }}
          cluster-name: ${{ secrets.cluster_name }}

      # Setup kubectl
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      # Deploy to AKS
      - name: Deploy to AKS
        uses: Azure/k8s-deploy@v4
        with:
          namespace: default
          manifests: |
            "kk/**"
          images: ${{ secrets.registry }}.azurecr.io/azure-vote-v2:${{ github.sha }}
          pull-images: true
